#pragma once

#define EDVWHHOOK_HWND_SHELL _T("EDVWHHOOK_HWND_SHELL")
#define EDVWHHOOK_HWND_SHELL _T("EDVWHHOOK_HWND_SHELL")
#define EDVWHHOOK_HWND_SHELL _T("EDVWHHOOK_HWND_SHELL")
#define EDVWHHOOK_HSHELL_ACTIVATESHELLWINDOW _T("EDVWHHOOK_HSHELL_ACTIVATESHELLWINDOW")
#define EDVWHHOOK_HSHELL_GETMINRECT _T("EDVWHHOOK_HSHELL_GETMINRECT")
#define EDVWHHOOK_HSHELL_LANGUAGE _T("EDVWHHOOK_HSHELL_LANGUAGE")
#define EDVWHHOOK_HSHELL_REDRAW _T("EDVWHHOOK_HSHELL_REDRAW")
#define EDVWHHOOK_HSHELL_TASKMAN _T("EDVWHHOOK_HSHELL_TASKMAN")
#define EDVWHHOOK_HSHELL_WINDOWACTIVATED _T("EDVWHHOOK_HSHELL_WINDOWACTIVATED")
#define EDVWHHOOK_HSHELL_WINDOWCREATED _T("EDVWHHOOK_HSHELL_WINDOWCREATED")
#define EDVWHHOOK_HSHELL_WINDOWDESTROYED _T("EDVWHHOOK_HSHELL_WINDOWDESTROYED")
#define EDVWHHOOK_HWND_SHELL _T("EDVWHHOOK_HWND_SHELL")
#define EDVWHHOOK_SHELL_REPLACED _T("EDVWHHOOK_SHELL_REPLACED")

#define EDVWHHOOK_HCBT_WINDOWCREATED _T("EDVWHHOOK_HCBT_WINDOWCREATED")
#define EDVWHHOOK_HCBT_WINDOWMOVED _T("EDVWHHOOK_HCBT_WINDOWMOVED")
#define EDVWHHOOK_HCBT_WINDOWDESTROYED _T("EDVWHHOOK_HCBT_WINDOWDESTROYED")

#define EDVWHHOOK_HKB_KBEVENT _T("EDVWHHOOK_HKB_KBEVENT")

#define EDVWHHOOK_HCWP_SHOWWINDOW _T("EDVWHHOOK_HCWP_SHOWWINDOW")
#define EDVWHHOOK_HCWP_SETFOCUS _T("EDVWHHOOK_HCWP_SETFOCUS")
#define EDVWHHOOK_HCBT_WINDOWFOCUSED _T("EDVWHHOOK_HCBT_WINDOWFOCUSED")
#define EDVWHHOOK_HCWR_SETFOCUS _T("EDVWHHOOK_HCWR_SETFOCUS")
#define EDVWHHOOK_EDV_REDIRECTFOCUS _T("EDVWHHOOK_EDV_REDIRECTFOCUS")
